# -*- coding: utf-8 -*-
"""Healthcare Data Reporting Automation using Python & Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dwj7nihV0rFuXfmrfBVuA-f4kEyIUlbx

# Import library and Load dataset
"""

import pandas as pd

df = pd.read_csv("/content/healthcare_dataset.csv")

"""# Remove duplicates"""

# Remove duplicates
df = df.drop_duplicates()

# Convert dates
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

# Create Length of Stay
df["Length of Stay"] = (
    df["Discharge Date"] -
    df["Date of Admission"]
).dt.days

"""# Average billing"""

avg_bill = (
    df.groupby("Medical Condition")["Billing Amount"]
      .mean()
      .reset_index()
)

patients = (
    df["Hospital"]
      .value_counts()
      .reset_index()
)

patients.columns = ["Hospital","Patients"]

admission = (
    df["Admission Type"]
      .value_counts()
      .reset_index()
)

admission.columns = ["Admission Type","Count"]

medicine = (
    df["Medication"]
      .value_counts()
      .reset_index()
)

medicine.columns = ["Medication","Count"]

stay = (
    df.groupby("Medical Condition")["Length of Stay"]
      .mean()
      .reset_index()
)

df.to_csv("cleaned_healthcare.csv", index=False)

with pd.ExcelWriter("report.xlsx") as writer:

    avg_bill.to_excel(
        writer,
        sheet_name="Average Billing",
        index=False
    )

    patients.to_excel(
        writer,
        sheet_name="Patients",
        index=False
    )

    admission.to_excel(
        writer,
        sheet_name="Admission",
        index=False
    )

    medicine.to_excel(
        writer,
        sheet_name="Medication",
        index=False
    )

    stay.to_excel(
        writer,
        sheet_name="Length of Stay",
        index=False
    )

